version: '3'
services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: ${COMPOSE_PROJECT_NAME}webserver
    image: ${COMPOSE_PROJECT_NAME}webserver
    ports:
      - ${PORT}:80
    external_links:
      - redis
      - mysql
    networks:
      - docker-default_default
    volumes:
      - ${DOCUMENT_ROOT-./www}:/usr/share/apache2/www
      - ${VHOSTS_DIR-./config/apache2/sites-enabled}:/etc/apache2/sites-enabled/
      - ${PHP_INI-./config/php/php.ini}:/etc/php/5.6/apache2/conf.d/php.ini
      - ./config/php/${APP_ENV}.ini:/etc/php/5.6/apache2/conf.d/${APP_ENV}.ini
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  redis:
    build: ./bin/redis
    container_name: ${COMPOSE_PROJECT_NAME}redis
    image: ${COMPOSE_PROJECT_NAME}redis
    restart: always
    volumes:
      - /data/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - docker-default_default
networks:
  docker-default_default:
    external: true
